<div class="grid gap-4 md:grid-cols-2">
    <div><label class="mb-1.5 block text-sm font-semibold">Tên cơ sở/tài sản</label><input name="property_name" value="{{ old('property_name', $setting->property_name) }}" required class="h-11 w-full rounded-lg border border-slate-200 px-3"></div>
    <div><label class="mb-1.5 block text-sm font-semibold">Tên chủ nhà</label><input name="landlord_name" value="{{ old('landlord_name', $setting->landlord_name) }}" required class="h-11 w-full rounded-lg border border-slate-200 px-3"></div>
    <div class="md:col-span-2"><label class="mb-1.5 block text-sm font-semibold">Địa chỉ tài sản</label><textarea name="property_address" required class="w-full rounded-lg border border-slate-200 p-3">{{ old('property_address', $setting->property_address) }}</textarea></div>
    <div><label class="mb-1.5 block text-sm font-semibold">Ngày sinh chủ nhà</label><input type="date" name="landlord_date_of_birth" value="{{ old('landlord_date_of_birth', $setting->landlord_date_of_birth?->toDateString()) }}" class="h-11 w-full rounded-lg border border-slate-200 px-3"></div>
    <div><label class="mb-1.5 block text-sm font-semibold">Số điện thoại chủ nhà</label><input name="landlord_phone" value="{{ old('landlord_phone', $setting->landlord_phone) }}" required class="h-11 w-full rounded-lg border border-slate-200 px-3"></div>
    <div><label class="mb-1.5 block text-sm font-semibold">CCCD chủ nhà</label><input name="landlord_identity_number" value="{{ old('landlord_identity_number', $setting->landlord_identity_number) }}" class="h-11 w-full rounded-lg border border-slate-200 px-3"></div>
    <div><label class="mb-1.5 block text-sm font-semibold">Ngày cấp</label><input type="date" name="landlord_identity_issued_at" value="{{ old('landlord_identity_issued_at', $setting->landlord_identity_issued_at?->toDateString()) }}" class="h-11 w-full rounded-lg border border-slate-200 px-3"></div>
    <div class="md:col-span-2"><label class="mb-1.5 block text-sm font-semibold">Nơi cấp</label><input name="landlord_identity_issued_by" value="{{ old('landlord_identity_issued_by', $setting->landlord_identity_issued_by) }}" class="h-11 w-full rounded-lg border border-slate-200 px-3"></div>
    <div class="md:col-span-2"><label class="mb-1.5 block text-sm font-semibold">Địa chỉ chủ nhà</label><textarea name="landlord_address" required class="w-full rounded-lg border border-slate-200 p-3">{{ old('landlord_address', $setting->landlord_address) }}</textarea></div>
</div>
