<?php

return [
    'Ngân hàng Việt Nam' => [
        'Agribank',
        'Vietcombank (VCB)',
        'VietinBank (CTG)',
        'BIDV',
        'ACB',
        'MB Bank (MBBank)',
        'Techcombank (TCB)',
        'VPBank',
        'TPBank',
        'Sacombank (STB)',
        'VIB',
        'HDBank',
        'SHB',
        'OCB',
        'MSB',
        'SeABank',
        'LPBank',
        'Eximbank',
        'Nam A Bank',
        'ABBank',
        'Bac A Bank',
        'BaoViet Bank',
        'BVBank',
        'KienlongBank',
        'NCB',
        'PGBank',
        'PVcomBank',
        'Saigonbank',
        'VietABank',
        'VietBank',
        'SCB',
        'Co-opBank',
        'VCBNeo',
        'MBV',
        'GPBank',
        'Vikki Digital Bank',
        'Ngân hàng Chính sách Xã hội (VBSP)',
        'Ngân hàng Phát triển Việt Nam (VDB)',
    ],
    'Ngân hàng nước ngoài tại Việt Nam' => [
        'HSBC Việt Nam',
        'Standard Chartered Việt Nam',
        'Shinhan Bank Việt Nam',
        'Woori Bank Việt Nam',
        'Hong Leong Bank Việt Nam',
        'Public Bank Việt Nam',
        'UOB Việt Nam',
        'CIMB Việt Nam',
    ],
    'Ví điện tử và Mobile Money' => [
        'MoMo',
        'ZaloPay',
        'ShopeePay',
        'Viettel Money',
        'VNPT Money',
        'MobiFone Money',
        'Ví VNPAY',
        'Payoo',
        '9Pay',
        'Ngân Lượng',
        'SmartPay',
        'PayME',
        'Foxpay',
    ],
];
